%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
#Camera.fx: 479.570576946
#Camera.fy: 479.570576946
#Camera.cx: 411.879719484
#Camera.cy: 288.668313855

#Original (unresized, uncropped)
# Camera.fx: 1150.96938467
# Camera.fy: 1150.96938467
# Camera.cx: 988.511326762
# Camera.cy: 692.803953253
Camera.fx: 699.915
Camera.fy: 699.915
Camera.cx: 666.448
Camera.cy: 365.97

Camera.width: 1280
Camera.height: 720


Camera.k1: 0
Camera.k2: -0
# we provide rectified image to orbslam
#Camera.k1: -0.171275
#Camera.k2: 0.0229987
Camera.p1: -0
Camera.p2: 0
Camera.k3: 0

CameraRight.fx: 700.217
CameraRight.fy: 700.217
CameraRight.cx: 632.683
CameraRight.cy: 369.145
#CameraRight.k1: -0.173171
#CameraRight.k2: 0.0247159


# Camera frames per second 
Camera.fps: 60

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

Camera.bf: 120

ThDepth: 35

# These parameters reduce camera input resolution, and crop them.
# Camera.WorkingResolution.Width: 800
# Camera.WorkingResolution.Height: 600
# Camera.ROI.x0: 0
# Camera.ROI.y0: 0
# Camera.ROI.width: 800
# Camera.ROI.height: 600

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 3000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

#MapFileName: "/tmp/test.map"
#Camera.topic: "/camera1/image_color"
#Camera.topic: "/camera/image_raw"
#Camera.compressed: 0
#Camera.ROS.ImageType: "color"
#ExternalReference.Mapping.frame1: "world"
#ExternalReference.Mapping.frame2: "velodyne"
Localization.frame1: "world"
Localization.frame2: "camera"

ExternalLocalization.OffsetKeyframes: 10
 
